name: ❓ Question
description: Leave your questions or ask for help about this Manager.
title: 'question: '
labels: [question]
body:
  - type: textarea
    attributes:
      label: Description
      description: Add a clear and detailed description of the question.
      placeholder: Attach images/videos if possible. These can be helpful in figuring out what the question is about.
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don't follow the checklist below!
      options:
        - label: I have written a short but informative title.
          required: true
        - label: I have written the title and contents in English.
          required: true